services:
  elasticsearch8.4:
    image: elasticsearch:8.4.0
    container_name: elasticsearch8.4
    restart: always
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./config:/usr/share/elasticsearch/config"    # 配置文件
      - "./data:/usr/share/elasticsearch/data"        # 数据文件
      - "./logs:/usr/share/elasticsearch/logs"        # 日志文件
    environment:
      - "TZ=${TZ}"
      - "discovery.type=single-node"      # 单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # 设置使用jvm内存大小
    networks:
      - docker