include :
  - etcd/3.5.9/compose-standalone.yml
  - jenkins/2.414/compose-standalone.yml
  - redis/6.2/compose-standalone.yml

volumes:
  config_directory: # 定义命名卷（配置文件）
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config # 宿主机路径
  project_directory: # 定义命名卷（项目路径）
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_DIRECTORY} # 宿主机路径

networks:
  docker:
    name: docker
    driver: bridge