include :
  - php/8.2/compose.yml
  - php/8.3/compose.yml
  - php/8.4/compose.yml
  - mysql/8.0/compose.yml
  - redis/6/compose.yml

volumes:
  config_directory: # 定义命名卷（配置文件）
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config # 宿主机路径
  project_directory: # 定义命名卷（项目路径）
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PROJECT_DIRECTORY} # 宿主机路径

networks:
  docker:
    name: docker
    driver: bridge