services:
  postgres18:
    image: postgres:18-alpine
    container_name: postgres18
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data" # 数据文件
    environment:
      - "TZ=${TZ}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "PGDATA=${PGDATA}"
    networks:
      - docker
