services:
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "TZ=${TZ}"
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}"  # MongoDB admin username
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}"  # MongoDB admin password
      - "ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}"        # mongo-express web username
      - "ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}"        # mongo-express web password
      - "ME_CONFIG_MONGODB_ENABLE_ADMIN=${ME_CONFIG_MONGODB_ENABLE_ADMIN}"    # 管理员能够访问所有数据库
      - "ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}"
    depends_on:
      - mongo6.0
    networks:
      - docker