services:
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.9
    container_name: etcd
    restart: always
    privileged: true
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes # 允许不用密码登录
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node1:2379 # 告知集群自己的客户端地址
    networks:
      - etcd-standalone

networks:
  etcd-standalone: