services:
  etcd-node-1:
    image: gcr.io/etcd-development/etcd:v3.5.9
    container_name: etcd-node-1
    restart: always
    privileged: true
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_NAME=etcd-node-1 # 当前节点名称
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-1:2379 # 告知集群自己的客户端地址
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 设置监听客户端通讯的URL列表
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-1:2380 # 告知集群自己集群通讯地址
      - ETCD_INITIAL_CLUSTER=etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380,etcd-node-3=http://etcd-node-3:2380 #集群成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER_STATE=new # 初始化集群状态
    networks:
      - docker

  etcd-node-2:
    image: gcr.io/etcd-development/etcd:v3.5.9
    container_name: etcd-node-2
    restart: always
    privileged: true
    ports:
      - "12379:2379"
      - "12380:2380"
    environment:
      - ETCD_NAME=etcd-node-2 # 当前节点名称
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-2:2379 # 告知集群自己的客户端地址
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 设置监听客户端通讯的URL列表
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-2:2380 # 告知集群自己集群通讯地址
      - ETCD_INITIAL_CLUSTER=etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380,etcd-node-3=http://etcd-node-3:2380 #集群成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER_STATE=new # 初始化集群状态
    networks:
      - docker

  etcd-node-3:
    image: gcr.io/etcd-development/etcd:v3.5.9
    container_name: etcd-node-3
    restart: always
    privileged: true
    ports:
      - "22379:2379"
      - "22380:2380"
    environment:
      - ETCD_NAME=etcd-node-3 # 当前节点名称
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd-node-3:2379 # 告知集群自己的客户端地址
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 # 设置监听客户端通讯的URL列表
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 # 用于监听伙伴通讯的URL列表
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd-node-3:2380 # 告知集群自己集群通讯地址
      - ETCD_INITIAL_CLUSTER=etcd-node-1=http://etcd-node-1:2380,etcd-node-2=http://etcd-node-2:2380,etcd-node-3=http://etcd-node-3:2380 #集群成员
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster # 集群的初始化集群记号
      - ETCD_INITIAL_CLUSTER_STATE=new # 初始化集群状态
    networks:
      - docker