services:
  acme:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        TZ: ${TZ}
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
    container_name: acme
    restart: always
    env_file:
      - "./.env"
    volumes:
      - "./logs:/var/log/acme"                       # 日志文件
      - "config_directory:/usr/config"               # 证书和 acme 账户数据
      - "project_directory:/usr/share/nginx/html"    # webroot challenge 目录
    networks:
      - docker
